"""add tag

Revision ID: c731055be562
Revises: 52b101eb4eb2
Create Date: 2025-11-16 23:12:22.774430

"""
from typing import Sequence, Union

import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c731055be562'
down_revision: Union[str, Sequence[str], None] = '52b101eb4eb2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tag',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Enum('EXPRESS', 'STANDARD', 'FRAGILE', 'HEAVY', 'INTERNATIONAL', 'DOMESTIC', 'TEMPERATURE_CONTROLLED', 'GIFT', 'RETURN', 'DUCUMENTS', name='tagname'), nullable=False),
    sa.Column('instruction', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shipment_tag',
    sa.Column('shipment_id', sa.Uuid(), nullable=False),
    sa.Column('tag_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipment.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ),
    sa.PrimaryKeyConstraint('shipment_id', 'tag_id')
    )
    # ### end Alembic commands ###

    op.execute(
        sa.text(
            """
            INSERT INTO tag (id, name, instruction) VALUES
            ('0a3f2b7e-2c56-4e89-8c1a-0f2d1b3a4c5d', 'EXPRESS', 'Prioritize delivery and accelerate processing for EXPRESS.'),
            ('1b4c5d6e-7f80-41a2-9b3c-4d5e6f708192', 'STANDARD', 'Process with standard service level for STANDARD.'),
            ('2c5d6e7f-8091-42b3-a4c5-5e6f708192a3', 'FRAGILE', 'Handle with extra care and avoid stacking for FRAGILE.'),
            ('3d6e7f80-912a-43c4-b5d6-6f708192a3b4', 'HEAVY', 'Use team lift or handling equipment for HEAVY.'),
            ('4e7f8091-a2b3-44d5-c6e7-708192a3b4c5', 'INTERNATIONAL', 'Include customs documents and compliance checks for INTERNATIONAL.'),
            ('5f8091a2-b3c4-45e6-d7f8-8192a3b4c5d6', 'DOMESTIC', 'Route via domestic network with standard paperwork for DOMESTIC.'),
            ('6091a2b3-c4d5-46f7-e809-92a3b4c5d6e7', 'TEMPERATURE_CONTROLLED', 'Maintain required temperature and monitor throughout for TEMPERATURE_CONTROLLED.'),
            ('7192a3b4-d5e6-4708-f91a-a3b4c5d6e7f8', 'GIFT', 'Mark as gift and omit pricing documents for GIFT.'),
            ('82a3b4c5-e6f7-4819-0a2b-b4c5d6e7f809', 'RETURN', 'Route to returns processing and verify RMA for RETURN.'),
            ('93b4c5d6-f708-492a-1b3c-c5d6e7f8091a', 'DUCUMENTS', 'Flat handling only with document protection for DUCUMENTS.');
            """
        )
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shipment_tag')
    op.drop_table('tag')
    # ### end Alembic commands ###
